import type { Metadata } from "next";
import "./globals.css";
import { Inter as FontSans } from 'next/font/google';
import { cn } from "@/lib/utils";
import QueryProvider from "@/providers/query-provider";
import Header from "./(client)/_components/header";
import Footer from "./(client)/_components/footer";

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
        <body
                className={cn(
                    'min-h-screen bg-background font-sans antialiased',
                    fontSans.variable
                )}>
      <QueryProvider>
        <section>
          <Header />
          <main>
        {children}
          </main>
          <Footer />
        </section>
      </QueryProvider>
      </body>
    </html>
  );
}
